### ISSUE TITLE
Revenge completely breaks on GrapheneOS after update

### ISSUE THREAD

**Issue by DavidRLTG** [revenge-mod/Revenge#24] opened 2024-03-09 09:52 UTC
I'm on GrapheneOS, Android 14, on Google Pixel 8.
After updating GrapheneOS, Vendetta/Revenge is constantly stopping and unable to work.
If it helps, here are the logs:

[Vendetta log 009b80a3df2e.txt]
(https://github.com/revenge-mod/Revenge/files/14545879/Vendetta.log.009b80a3df2e.txt)

And the app constantly keeps stopping in the background, where I get these logs:
```
type: crash
osVersion: google/shiba/shiba:14/AP1A.240305.019.A1/2024030800:user/release-keys
package: dev.beefers.vendetta:219021
process: dev.beefers.vendetta
processUptime: 0 + 0 ms
installer: dev.beefers.vendetta.manager

signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000000

backtrace:
      #00 pc 000000000005d7c8  /apex/com.android.runtime/lib64/bionic/libc.so (__strlen_aarch64_mte+8) (BuildId: e0e450f9d8a33cfa56bcb9d31a17cf57)
      #01 pc 0000000000008cdc  /data/app/~~2fFHDpFkbKZLm7hnSdbSmw==/dev.beefers.vendetta-4fJckK0cm8AbReqFNN7pew==/base.apk!liblspatch.so (offset 0x358c000) (BuildId: d4149c5900fe425a34b6c94a360ee7f13abc85a5)
```

Not sure if this is the new App Freezing issue, or a GrapheneOS issue.
But, I am on Version 219.

**Comment by PalmDevs** [comment] 2024-03-09 10:15
Dupe of #22

**Closed by PalmDevs** 2024-03-09 10:15 UTC
